apiVersion: v2
name: mlflow
description: A Helm chart for MLFlow
type: application
version: 1.0.0
appVersion: 1.0.0
keywords:
  - mlflow
home: https://mlflow.org/
icon: https://mlflow.org/docs/latest/_static/MLflow-logo-final-black.png
source:
  - https://github.com/cetic/helm-mlflow
maintainers:
  - name: YarinNago
    email: yarinago@gmail.com
    url: https://github.com/yarinago
{{- if .Values.volumes }}
dependencies:
{{ toYaml .Values.dependencies | indent 1 }}
