{{- if .Values.ingress.enabled -}}
{{- $fullName := include "mlflow.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: v1
kind: Ingress
metadata:
  name: {{ template "mlflow.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  managed-by: {{ .Release.Service }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }} # mlflow.dr.com
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ template "mlflow.fullname" . }}-service
              servicePort: {{ .Values.ingress.servicePort }} # 8080
{{- end }}
