apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    name: {{ include "mlflow.name" . }}
  # instance: {{ .Release.Name }}
    managed-by: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 2 }}
{{- end }}
spec:
  type: {{ .Values.service.type }} # NodePort
  {{- if and .Values.service.loadBalancerIP (eq .Values.service.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ with .Values.service.loadBalancerSourceRanges }}
{{ toYaml . | indent 2 }}
{{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }} # Port number exposed internally in cluster
      NodePort: {{ .Values.service.NodePort }} # A static port assigned on each the node
      targetPort: {{ .Values.service.targetPort }} # The container port to send requests to
  selector:
    name: {{ include "mlflow.name" . }}
  # instance: {{ .Release.Name }}
